export const SOCIAL_MEDIA_FB_USERNAME = ""
export const SOCIAL_MEDIA_IG_USERNAME = ""
export const SOCIAL_MEDIA_YT_USERNAME = ""
export const SOCIAL_MEDIA_TW_USERNAME = ""
export const SOCIAL_MEDIA_LI_USERNAME = ""
